import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../services/database_service.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'en';
  final DatabaseService dbService = DatabaseService();

  String get currentLanguage => _currentLanguage;

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('preferred_language') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    if (_currentLanguage == languageCode) return;
    
    _currentLanguage = languageCode;
    notifyListeners(); // Immediate UI update

    // Background persistent updates
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('preferred_language', languageCode);
    
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      await DatabaseService().updateUserLanguage(user.uid, languageCode);
    }
  }

  Future<void> syncWithFirestore(String userId) async {
    final cloudLang = await DatabaseService().getUserLanguage(userId);
    if (cloudLang != null && cloudLang != _currentLanguage) {
      _currentLanguage = cloudLang;
      notifyListeners();
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('preferred_language', cloudLang);
    }
  }

  // Simple UI translation map for core labels
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'nav_home': 'Home',
      'nav_map': 'Map',
      'nav_scanner': 'Scanner',
      'nav_profile': 'Profile',
      'scan_button': 'SCAN WASTE',
      'report_waste': 'Report Waste Pile',
      'report_waste_msg': 'Tap anywhere on the map to report waste.',
      'add_bin': 'Add Smart Bin',
      'contribute': 'CONTRIBUTE',
      'sign_out': 'Sign Out',
      'lang_selector': 'Preferred Language',
      'impact_title': 'Your Eco-Impact',
      'planet_saved': 'Planet Saved',
      'total_waste': 'Total Waste Diverted',
      'points': 'POINTS',
      'rank': 'RANK',
      'level': 'LEVEL',
      'recent_activity': 'Recent Activity',
      'account_settings': 'Account Settings',
      'profile_title': 'Your Profile',
      'no_activity': 'No activity yet. Start recycling!',
      'notifications': 'Notifications',
      'help_support': 'Help & Support',
      'progress_overview': 'Progress Overview',
      'recycling_tips': 'Recycling Tips',
      'map_title': 'Waste Intelligence Map',
      'contribute_how': 'How would you like to contribute?',
      'report_waste_title': 'Report Waste Pile',
      'report_waste_sub': 'Report trash that needs picking up.',
      'add_bin_subtitle': 'Map a permanent bin for the community.',
      'location_method': 'Location Method',
      'use_current_location': 'Use Current Location',
      'select_on_map': 'Select on Map',
      'confirm_location': 'Confirm Location',
      'submit_report': 'SUBMIT REPORT',
      'waste_type': 'Waste Type',
      'notes': 'Notes',
      'take_photo': 'Take Photo',
      'navigate': 'NAVIGATE (PROTOTYPE)',
      'remove_bin': 'REMOVE FROM MAP',
      'delete_report': 'DELETE REPORT',
      'cancel': 'CANCEL',
      'remove': 'REMOVE',
      'delete': 'DELETE',
      'remove_bin_confirm': 'Are you sure you want to remove this bin from the community map?',
      'delete_report_confirm': 'This action will permanently remove your report from the map.',
    },
    'hi': {
      'nav_home': 'मुख्य पृष्ठ',
      'nav_map': 'मानचित्र',
      'nav_scanner': 'स्कैनर',
      'nav_profile': 'प्रोफ़ाइल',
      'scan_button': 'कचरा स्कैन करें',
      'report_waste': 'कचरे का ढेर रिपोर्ट करें',
      'report_waste_msg': 'कचरे की रिपोर्ट करने के लिए मानचित्र पर कहीं भी टैप करें।',
      'add_bin': 'स्मार्ट बिन जोड़ें',
      'contribute': 'योगदान दें',
      'sign_out': 'साइन आउट',
      'lang_selector': 'पसंदीदा भाषा',
      'impact_title': 'आपका प्रभाव',
      'planet_saved': 'ग्रह रक्षित',
      'total_waste': 'कुल कचरा मोड़ा गया',
      'points': 'अंक',
      'rank': 'श्रेणी',
      'level': 'स्तर',
      'recent_activity': 'हाल की गतिविधि',
      'account_settings': 'अकाउंट सेटिंग्स',
      'profile_title': 'आपकी प्रोफ़ाइल',
      'no_activity': 'अभी तक कोई गतिविधि नहीं। रीसायकल शुरू करें!',
      'notifications': 'सूचनाएं',
      'help_support': 'सहायता और समर्थन',
      'progress_overview': 'प्रगति अवलोकन',
      'recycling_tips': 'रीसायकलिंग टिप्स',
      'map_title': 'अपशिष्ट खुफिया मानचित्र',
      'contribute_how': 'आप कैसे योगदान देना चाहते हैं?',
      'report_waste_title': 'कचरे का ढेर रिपोर्ट करें',
      'report_waste_sub': 'उस कचरे की रिपोर्ट करें जिसे उठाने की जरूरत है।',
      'add_bin_subtitle': 'समुदाय के लिए एक स्थायी बिन का नक्शा बनाएं।',
      'location_method': 'स्थान विधि',
      'use_current_location': 'वर्तमान स्थान का उपयोग करें',
      'select_on_map': 'मानचित्र पर चुनें',
      'confirm_location': 'स्थान की पुष्टि करें',
      'submit_report': 'रिपोर्ट सबमिट करें',
      'waste_type': 'कचरे का प्रकार',
      'notes': 'नोट्स',
      'take_photo': 'फ़ोटो लें',
      'navigate': 'नेविगेट करें (प्रोटोटाइप)',
      'remove_bin': 'मानचित्र से हटाएं',
      'delete_report': 'रिपोर्ट हटाएं',
      'cancel': 'रद्द करें',
      'remove': 'हटाएं',
      'delete': 'मिटाएं',
      'remove_bin_confirm': 'क्या आप वाकई इस बिन को सामुदायिक मानचित्र से हटाना चाहते हैं?',
      'delete_report_confirm': 'यह क्रिया मानचित्र से आपकी रिपोर्ट स्थायी रूप से हटा देगी।',
    },
    'fr': {
      'nav_home': 'Accueil',
      'nav_map': 'Carte',
      'nav_scanner': 'Scanner',
      'nav_profile': 'Profil',
      'scan_button': 'SCANNER LES DÉCHETS',
      'report_waste': 'Signaler un tas de déchets',
      'report_waste_msg': 'Appuyez n\'importe où sulla carte pour signaler des déchets.',
      'add_bin': 'Ajouter un bac intelligent',
      'contribute': 'CONTRIBUER',
      'sign_out': 'Se déconnecter',
      'lang_selector': 'Langue préférée',
      'impact_title': 'Votre Éco-Impact',
      'planet_saved': 'Planète Sauvée',
      'total_waste': 'Déchets Totaux Détournés',
      'points': 'POINTS',
      'rank': 'RANG',
      'level': 'NIVEAU',
      'recent_activity': 'Activité Récente',
      'account_settings': 'Paramètres du Compte',
      'profile_title': 'Votre Profil',
      'no_activity': 'Aucune activité pour le moment.',
      'notifications': 'Notifications',
      'help_support': 'Aide et Support',
      'progress_overview': 'Aperçu des Progrès',
      'recycling_tips': 'Conseils de Recyclage',
      'map_title': 'Carte d\'Intelligence des Déchets',
      'contribute_how': 'Comment souhaitez-vous contribuer ?',
      'report_waste_title': 'Signaler un tas de déchets',
      'report_waste_sub': 'Signalez les déchets à ramasser.',
      'add_bin_subtitle': 'Cartographiez une poubelle permanente pour la communauté.',
      'location_method': 'Méthode de localisation',
      'use_current_location': 'Utiliser ma position actuelle',
      'select_on_map': 'Sélectionner sur la carte',
      'confirm_location': 'Confirmer la position',
      'submit_report': 'SOUMETTRE LE RAPPORT',
      'waste_type': 'Type de déchet',
      'notes': 'Notes',
      'take_photo': 'Prendre une photo',
      'navigate': 'NAVIGUER (PROTOTYPE)',
      'remove_bin': 'RETIRER DE LA CARTE',
      'delete_report': 'SUPPRIMER LE RAPPORT',
      'cancel': 'ANNULER',
      'remove': 'RETIRER',
      'delete': 'SUPPRIMER',
      'remove_bin_confirm': 'Voulez-vous vraiment retirer cette poubelle de la carte ?',
      'delete_report_confirm': 'Cette action supprimera définitivement votre rapport de la carte.',
    },
    'es': {
      'nav_home': 'Inicio',
      'nav_map': 'Mapa',
      'nav_scanner': 'Escáner',
      'nav_profile': 'Perfil',
      'scan_button': 'ESCANEAR RESIDUOS',
      'report_waste': 'Reportar montón de residuos',
      'report_waste_msg': 'Toque en cualquier lugar del mapa para reportar residuos.',
      'add_bin': 'Añadir papelera inteligente',
      'contribute': 'CONTRIBUIR',
      'sign_out': 'Cerrar sesión',
      'lang_selector': 'Idioma preferido',
      'impact_title': 'Tu Impacto Ecológico',
      'planet_saved': 'Planeta Salvado',
      'total_waste': 'Residuos Totales Divertidos',
      'points': 'PUNTOS',
      'rank': 'RANGO',
      'level': 'NIVEL',
      'recent_activity': 'Actividad Reciente',
      'account_settings': 'Configuración de la Cuenta',
      'profile_title': 'Tu Perfil',
      'no_activity': 'Sin actividad aún. ¡Empieza a reciclar!',
      'notifications': 'Notificaciones',
      'help_support': 'Ayuda y Soporte',
      'progress_overview': 'Resumen de Progreso',
      'recycling_tips': 'Consejos de Reciclaje',
      'map_title': 'Mapa de Inteligencia de Residuos',
      'contribute_how': '¿Cómo te gustaría contribuir?',
      'report_waste_title': 'Reportar montón de residuos',
      'report_waste_sub': 'Reporta basura que necesita recogida.',
      'add_bin_subtitle': 'Mapea un contenedor para la comunidad.',
      'location_method': 'Método de ubicación',
      'use_current_location': 'Usar ubicación actual',
      'select_on_map': 'Seleccionar en el mapa',
      'confirm_location': 'Confirmar ubicación',
      'submit_report': 'ENVIAR REPORTE',
      'waste_type': 'Tipo de residuo',
      'notes': 'Notas',
      'take_photo': 'Tomar foto',
      'navigate': 'NAVEGAR (PROTOTIPO)',
      'remove_bin': 'QUITAR DEL MAPA',
      'delete_report': 'ELIMINAR REPORTE',
      'cancel': 'CANCELAR',
      'remove': 'QUITAR',
      'delete': 'ELIMINAR',
      'remove_bin_confirm': '¿Seguro que quieres quitar este contenedor del mapa?',
      'delete_report_confirm': 'Esta acción eliminará permanentemente tu reporte del mapa.',
    },
    'ja': {
      'nav_home': 'ホーム',
      'nav_map': 'マップ',
      'nav_scanner': 'スキャナー',
      'nav_profile': 'プロフィール',
      'scan_button': '廃棄物をスキャン',
      'report_waste': '廃棄物の山を報告',
      'report_waste_msg': '地図上の任意の場所をタップして廃棄物を報告してください。',
      'add_bin': 'スマートゴミ箱を追加',
      'contribute': '貢献する',
      'sign_out': 'サインアウト',
      'lang_selector': '希望の言語',
      'impact_title': 'エコ・インパクト',
      'planet_saved': '守られた地球',
      'total_waste': '削減された総廃棄物量',
      'points': 'ポイント',
      'rank': 'ランク',
      'level': 'レベル',
      'recent_activity': '最近の活動',
      'account_settings': 'アカウント設定',
      'profile_title': 'プロフィール',
      'no_activity': '活動はまだありません。',
      'notifications': '通知',
      'help_support': 'ヘルプとサポート',
      'progress_overview': '進捗状況',
      'recycling_tips': 'リサイクルのヒント',
      'map_title': '廃棄物インテリジェンスマップ',
      'contribute_how': 'どのように貢献しますか？',
      'report_waste_title': '廃棄物の山を報告',
      'report_waste_sub': '回収が必要なゴミを報告してください。',
      'add_bin_subtitle': 'コミュニティのための常設ゴミ箱をマップします。',
      'location_method': '場所の選択方法',
      'use_current_location': '現在地を使用',
      'select_on_map': 'マップ上で選択',
      'confirm_location': '場所を確認',
      'submit_report': 'レポートを送信',
      'waste_type': '廃棄物の種類',
      'notes': 'メモ',
      'take_photo': '写真を撮る',
      'navigate': 'ナビゲート（試作品）',
      'remove_bin': 'マップから削除',
      'delete_report': 'レポートを削除',
      'cancel': 'キャンセル',
      'remove': '削除',
      'delete': '消去',
      'remove_bin_confirm': 'このゴミ箱をコミュニティマップから削除してよろしいですか？',
      'delete_report_confirm': 'この操作により、マップからレポートが完全に削除されます。',
    },
    'it': {
      'nav_home': 'Home',
      'nav_map': 'Mappa',
      'nav_scanner': 'Scanner',
      'nav_profile': 'Profilo',
      'scan_button': 'SCANNERIZZA RIFIUTI',
      'report_waste': 'Segnala ammasso di rifiuti',
      'report_waste_msg': 'Tocca un punto qualsiasi sulla mappa per segnalare i rifiuti.',
      'add_bin': 'Aggiungi cestino smart',
      'contribute': 'CONTRIBUISCI',
      'sign_out': 'Disconnetti',
      'lang_selector': 'Lingua preferita',
      'impact_title': 'Tuo Impatto Eco',
      'planet_saved': 'Pianeta Salvato',
      'total_waste': 'Rifiuti Totali Dirottati',
      'points': 'PUNTI',
      'rank': 'GRADO',
      'level': 'LIVELLO',
      'recent_activity': 'Attività Recente',
      'account_settings': 'Impostazioni Account',
      'profile_title': 'Il tuo Profilo',
      'no_activity': 'Nessuna attività. Inizia a riciclare!',
      'notifications': 'Notifiche',
      'help_support': 'Aiuto e Supporto',
      'progress_overview': 'Panoramica Progressi',
      'recycling_tips': 'Consigli Riciclaggio',
      'map_title': 'Mappa Intelligente dei Rifiuti',
      'contribute_how': 'Come vorresti contribuire?',
      'report_waste_title': 'Segnala ammasso di rifiuti',
      'report_waste_sub': 'Segnala i rifiuti da raccogliere.',
      'add_bin_subtitle': 'Mappa un cestino permanente per la comunità.',
      'location_method': 'Metodo di localizzazione',
      'use_current_location': 'Usa posizione attuale',
      'select_on_map': 'Seleziona sulla mappa',
      'confirm_location': 'Conferma posizione',
      'submit_report': 'INVIA SEGNALAZIONE',
      'waste_type': 'Tipo di rifiuto',
      'notes': 'Note',
      'take_photo': 'Scatta foto',
      'navigate': 'NAVIGA (PROTOTIPO)',
      'remove_bin': 'RIMUOVI DALLA MAPPA',
      'delete_report': 'ELIMINA SEGNALAZIONE',
      'cancel': 'ANNULLA',
      'remove': 'RIMUOVI',
      'delete': 'ELIMINA',
      'remove_bin_confirm': 'Sei sicuro di voler rimuovere questo cestino dalla mappa?',
      'delete_report_confirm': 'Questa azione rimuoverà definitivamente la tua segnalazione dalla mappa.',
    },
  };

  String getText(String key) {
    return _localizedValues[_currentLanguage]?[key] ?? _localizedValues['en']![key] ?? key;
  }
}
